<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Helen Duncan">
<meta name="author" content="Bill Finnegan">
<meta name="author" content="Luke Hare">
<meta name="author" content="Camila Rangel Smith">
<meta name="author" content="Sam Van Stroud">
<meta name="dcterms.date" content="2022-03-09">
<meta name="keywords" content="data exploration, data wrangling, data visualisation, digital humanities">

<title>Turing Data Stories - Desert Island Discs - Famous people and their musical tastes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Turing Data Stories</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/alan-turing-institute/turingdatastories" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Desert Island Discs - Famous people and their musical tastes</h1>
                      </div>
  </div>
    
  <div class="quarto-title-meta-author">
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-heading">Affiliations</div>
    
      <div class="quarto-title-meta-contents">
      <p class="author"><a href="https://www.turing.ac.uk/people/research-engineering/helen-duncan">Helen Duncan</a> </p>
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              The Alan Turing Institute
            </p>
        </div>
        <div class="quarto-title-meta-contents">
      <p class="author"><a href="https://www.ox.ac.uk/news-and-events/find-an-expert/bill-finnegan">Bill Finnegan</a> </p>
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              University of Oxford
            </p>
          <p class="affiliation">
              The Alan Turing Institute
            </p>
        </div>
        <div class="quarto-title-meta-contents">
      <p class="author"><a href="https://www.turing.ac.uk/people/research-engineering/luke-hare">Luke Hare</a> </p>
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              The Alan Turing Institute
            </p>
        </div>
        <div class="quarto-title-meta-contents">
      <p class="author"><a href="https://www.turing.ac.uk/people/research-engineering/camila-rangel-smith">Camila Rangel Smith</a> </p>
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              The Alan Turing Institute
            </p>
        </div>
        <div class="quarto-title-meta-contents">
      <p class="author"><a href="https://www.turing.ac.uk/people/sam-van-stroud">Sam Van Stroud</a> </p>
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              University College London
            </p>
        </div>
      </div>

  <div class="quarto-title-meta">

        
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">March 9, 2022</p>
      </div>
    </div>
    
      
    </div>
    
  <div>
    <div class="abstract">
      <div class="abstract-title">Abstract</div>
      As the iconic BBC radio programme turns 80, we explore notable people and the music that tells the stories of their lives.
    </div>
  </div>
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="reviewers" class="level3">
<h3 class="anchored" data-anchor-id="reviewers">Reviewers</h3>
<ul>
<li>Ed Chalstrey. The Alan Turing Institute.</li>
<li>Markus Hauru. The Alan Turing Institute.</li>
</ul>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p><a href="https://www.bbc.co.uk/programmes/b006qnmr">Desert Island Discs</a> is a long-running BBC radio programme and has become an invaluable archive of notable people and musical tastes over the past eight decades. This data story combines a new public dataset of all the guests and their musical selections extracted from the BBC archive with open datasets on people and music from Wikipedia and Spotify. We explore aspects of the people and music over time as well as the relationships between people and music through network analysis.</p>
</section>
<section id="background" class="level1">
<h1>Background</h1>
<p>In 1942, a new programme appeared on the airwaves of the BBC that was created and presented by Roy Plomley. The format was simple – a guest shared eight songs that they would want to be stuck with for the rest of their life if exiled to a desert island. After a hiatus from 1946 to 1951, the programme returned with some new innovations: at the end of each episode the castaway chooses a book, a luxury, and one song to save from the waves. The show was hosted by Plomley until his death in 1985, followed by Michael Parkinson, Sue Lawley, Kirsty Young, and Lauren Laverne.</p>
<p>Now considered a <a href="https://global.oup.com/academic/product/defining-the-discographic-self-9780197266175?cc=gb&amp;lang=en&amp;">cultural touchstone</a>, there have been over 3,200 episodes of Desert Island Discs. An invitation to be castaway is a sign of success in your field, whether that is art, academia, business, government or sport. Most episodes feature a single castaway, but sometimes multiple guests are castaway together, especially double acts like Morecambe and Wise or Ant and Dec.&nbsp;8% of castaways have appeared on the show more than once, with national treasure David Attenborough sharing a record four appearances with comedian/actor Arthur Askey.</p>
</section>
<section id="data" class="level1">
<h1>Data</h1>
<p><a href="https://twitter.com/andrewgustar">Andrew Gustar</a>, who conducts statistical research into music history, compiled a dataset of castaways and discs from the BBC Radio 4 archive. This data, which is now <a href="https://hcommons.org/deposits/item/hc:37503/">available online</a>, was the basis for Andrew’s <a href="https://www.musichistorystats.com/desert-island-discs/">analysis</a> exploring the most popular songs and artists, as well as the gender of the castaways. This data story includes information about an additional 60 episodes from February 2020 to August 2021 (gathered from <a href="https://en.wikipedia.org/wiki/List_of_Desert_Island_Discs_episodes">Wikipedia</a> and the <a href="https://www.bbc.co.uk/programmes/b006qnmr/episodes/player">BBC website</a>). It also combines the episode data with additional information about people and music. For people, we are using <a href="https://www.wikidata.org/wiki/Wikidata:Main_Page">Wikidata</a>, a repository of structured data from Wikipedia. For music, we are using <a href="https://developer.spotify.com/">Spotify</a> to get genre and other information about selected tunes.</p>
<p>Rather get into the details of how we pulled this dataset together, we want to keep this data story focused on the data analysis. The source code for the <code>wikipeople</code> package is available <a href="https://github.com/samvanstroud/wikipeople">on Github</a>, and the package is also on <a href="https://pypi.org/project/wikipeople/">PyPI</a>. It also takes a few hours to run all the requests for all the castaways and discs in our dataset, so we’ve done this once, and published the resulting dataset online. You can reproduce our work or just download the combined data at <a href="https://hcommons.org/deposits/item/hc:42511/">Humanities Commons</a>.</p>
<section id="python-setup" class="level2">
<h2 class="anchored" data-anchor-id="python-setup">Python setup</h2>
<p>Let’s get started by importing the packages that we’ll need for this story.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:01:59.833329Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:01:57.160334Z&quot;}" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> ast</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> collections</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> itertools</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> networkx <span class="im">as</span> nx</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pycountry <span class="im">as</span> pc</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pycountry_convert <span class="im">as</span> pcc</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>sns.<span class="bu">set</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="loading-the-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-the-data">Loading the data</h2>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:12.888616Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:01:59.835841Z&quot;}" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a> hc_data_url <span class="op">=</span> (</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"https://hcommons.org/deposits/download/hc:42512/CONTENT/desert_island_discs.xlsx"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a> )</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>castaways_df <span class="op">=</span> pd.read_excel(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    hc_data_url,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    sheet_name<span class="op">=</span><span class="st">"castaways"</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    parse_dates<span class="op">=</span>[<span class="st">"date"</span>, <span class="st">"date_of_birth"</span>],</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    index_col<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>)  <span class="co"># castaways, discs, spotify_data</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>castaways_df[<span class="st">"year"</span>] <span class="op">=</span> [i.year <span class="cf">for</span> i <span class="kw">in</span> castaways_df[<span class="st">"date"</span>].dt.date]</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>castaways_df.head(<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">episode_ref</th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">castaway_ref</th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">std_name</th>
<th data-quarto-table-cell-role="th">gender</th>
<th data-quarto-table-cell-role="th">profession</th>
<th data-quarto-table-cell-role="th">country_of_citizenship</th>
<th data-quarto-table-cell-role="th">place_of_birth</th>
<th data-quarto-table-cell-role="th">country_of_birth</th>
<th data-quarto-table-cell-role="th">date_of_birth</th>
<th data-quarto-table-cell-role="th">favTrack</th>
<th data-quarto-table-cell-role="th">luxury</th>
<th data-quarto-table-cell-role="th">book</th>
<th data-quarto-table-cell-role="th">wiki_link</th>
<th data-quarto-table-cell-role="th">link</th>
<th data-quarto-table-cell-role="th">year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2828</td>
<td>1942-01-29</td>
<td>2855</td>
<td>Vic Oliver</td>
<td>vic oliver</td>
<td>male</td>
<td>['actor', 'performing artist', 'artist', 'prof...</td>
<td>Austria-Hungary</td>
<td>Vienna</td>
<td>Austria</td>
<td>1898-07-08</td>
<td>NA by NA</td>
<td>NaN</td>
<td>NaN</td>
<td>https://en.wikipedia.org/wiki/Vic_Oliver</td>
<td>https://www.bbc.co.uk/programmes/p009y0nq</td>
<td>1942</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
</section>
<section id="episodes" class="level1">
<h1>Episodes</h1>
<p>Our dataset runs from January 1942 through to August 2021, when the programme took a break for the summer. We can use the episode and castaway reference numbers to get the totals for each.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:12.903558Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:12.891595Z&quot;}" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(castaways_df[<span class="st">"episode_ref"</span>].nunique())</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(castaways_df[<span class="st">"castaway_ref"</span>].nunique())</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>castaway_count <span class="op">=</span> castaways_df[<span class="st">"castaway_ref"</span>].value_counts().to_frame()</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">len</span>(castaway_count[(castaway_count[<span class="st">"castaway_ref"</span>] <span class="op">&gt;</span> <span class="dv">1</span>)]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>3211
2950
241</code></pre>
</div>
</div>
<p>So over the course of 3,211 episodes, we’ve had 2,950 castaways, with 241 people appearing on the programme more than once.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:13.248150Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:12.906072Z&quot;}" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>hosts <span class="op">=</span> [</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Roy Plomley"</span>, <span class="st">"29/01/1942"</span>, <span class="st">"11/05/1985"</span>),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Michael Parkinson"</span>, <span class="st">"05/01/1986"</span>, <span class="st">"13/03/1988"</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Sue Lawley"</span>, <span class="st">"27/03/1988"</span>, <span class="st">"27/08/2006"</span>),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Kirsty Young"</span>, <span class="st">"01/10/2006"</span>, <span class="st">"28/09/2018"</span>),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Lauren Laverne"</span>, <span class="st">"05/10/2018"</span>, <span class="va">None</span>),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">3</span>), dpi<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>n_bins <span class="op">=</span> castaways_df.year.<span class="bu">max</span>() <span class="op">-</span> castaways_df.year.<span class="bu">min</span>() <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>bins <span class="op">=</span> np.linspace(castaways_df.year.<span class="bu">min</span>(), castaways_df.year.<span class="bu">max</span>() <span class="op">+</span> <span class="dv">1</span>, n_bins <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>plt.hist(castaways_df.year, bins<span class="op">=</span>bins, color<span class="op">=</span>sns.color_palette(<span class="st">"Paired"</span>, <span class="dv">10</span>)[<span class="dv">5</span>])</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>_, ymax <span class="op">=</span> plt.ylim()</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> host <span class="kw">in</span> hosts:</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    year <span class="op">=</span> pd.to_datetime(host[<span class="dv">1</span>], infer_datetime_format<span class="op">=</span><span class="va">True</span>).year</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    plt.plot([year, year], [<span class="dv">0</span>, ymax <span class="op">*</span> <span class="fl">1.2</span>], color<span class="op">=</span><span class="st">"black"</span>, ls<span class="op">=</span><span class="st">"solid"</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> host[<span class="dv">0</span>] <span class="op">==</span> <span class="st">"Michael Parkinson"</span>:</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>        plt.annotate(host[<span class="dv">0</span>].replace(<span class="st">" "</span>, <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>), xy<span class="op">=</span>(year <span class="op">-</span> <span class="dv">8</span>, ymax))</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>        plt.annotate(host[<span class="dv">0</span>].replace(<span class="st">" "</span>, <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>), xy<span class="op">=</span>(year <span class="op">+</span> <span class="fl">0.5</span>, ymax))</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Year"</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Number of shows"</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">False</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-03-09-Desert-Island-Discs_files/figure-html/cell-5-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Plotting the episodes, you can immediately see the long run of the programme, minus a small hiatus after WWII. This plot also illustrates the long period of time that Plomley served as host, which accounts for the majority of episodes.</p>
</section>
<section id="castaways" class="level1">
<h1>Castaways</h1>
<section id="plotting-functions" class="level2">
<h2 class="anchored" data-anchor-id="plotting-functions">Plotting functions</h2>
<p>In order to look at the castaways who have been on the show in more detail, lets define some functions. These will help us to aggregate episodes in the same year, and then plot summary metrics as a function of year.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:13.311117Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:13.250246Z&quot;}" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># functions to help make stacked plots over time</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> normalize_rows(df):</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> df.div(df.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>), axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> df.fillna(<span class="dv">0</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> df</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cumulative_columns(df):</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co">    Loop through columns and calculate running totals</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co">    per row.</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># for each column (except the first)</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, col <span class="kw">in</span> <span class="bu">enumerate</span>(df):</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> i <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>        <span class="co"># add the previous column to this column</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>        df[col] <span class="op">+=</span> df[df.columns[i <span class="op">-</span> <span class="dv">1</span>]]</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> df</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> moving_average(df, n<span class="op">=</span><span class="dv">3</span>):</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> df.rolling(window<span class="op">=</span>n).mean()  <span class="co"># moving average</span></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> df.dropna(how<span class="op">=</span><span class="st">"all"</span>)  <span class="co"># drop lost columns</span></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> df</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_timeplot(</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>    df, ymin<span class="op">=</span><span class="dv">0</span>, horiz_line_y<span class="op">=</span><span class="dv">0</span>, leg_title<span class="op">=</span><span class="st">""</span>, y_title<span class="op">=</span><span class="st">"Fraction of Castaways"</span></span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>):</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>    c <span class="op">=</span> sns.color_palette(<span class="st">"Paired"</span>, <span class="bu">max</span>(<span class="dv">4</span>, <span class="bu">len</span>(df.columns)))</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>    plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">3</span>), dpi<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>    plt.gca().set_facecolor(c[<span class="dv">0</span>])</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>    xs <span class="op">=</span> df.index</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, col <span class="kw">in</span> <span class="bu">enumerate</span>(<span class="bu">reversed</span>(df.columns)):</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>        plt.fill_between(</span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a>            xs, df[col], interpolate<span class="op">=</span><span class="va">False</span>, color<span class="op">=</span>c[i], label<span class="op">=</span>col, alpha<span class="op">=</span><span class="fl">1.0</span></span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> horiz_line_y <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>        plt.plot(</span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>            plt.xlim(),</span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a>            [horiz_line_y, horiz_line_y],</span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a>            color<span class="op">=</span><span class="st">"black"</span>,</span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a>            ls<span class="op">=</span>((<span class="dv">0</span>, (<span class="dv">10</span>, <span class="dv">5</span>))),</span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>            lw<span class="op">=</span><span class="fl">1.5</span>,</span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">"Year"</span>, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(y_title, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb6-60"><a href="#cb6-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-61"><a href="#cb6-61" aria-hidden="true" tabindex="-1"></a>    plt.xticks(fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb6-62"><a href="#cb6-62" aria-hidden="true" tabindex="-1"></a>    plt.yticks(fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb6-63"><a href="#cb6-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-64"><a href="#cb6-64" aria-hidden="true" tabindex="-1"></a>    plt.xlim(df.index[<span class="dv">0</span>], df.index[<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb6-65"><a href="#cb6-65" aria-hidden="true" tabindex="-1"></a>    plt.ylim(ymin, <span class="dv">1</span>)</span>
<span id="cb6-66"><a href="#cb6-66" aria-hidden="true" tabindex="-1"></a>    leg <span class="op">=</span> plt.legend(</span>
<span id="cb6-67"><a href="#cb6-67" aria-hidden="true" tabindex="-1"></a>        loc<span class="op">=</span><span class="st">"upper left"</span>,</span>
<span id="cb6-68"><a href="#cb6-68" aria-hidden="true" tabindex="-1"></a>        bbox_to_anchor<span class="op">=</span>(<span class="fl">1.01</span>, <span class="fl">1.01</span>),</span>
<span id="cb6-69"><a href="#cb6-69" aria-hidden="true" tabindex="-1"></a>        fontsize<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb6-70"><a href="#cb6-70" aria-hidden="true" tabindex="-1"></a>        facecolor<span class="op">=</span><span class="st">"white"</span>,</span>
<span id="cb6-71"><a href="#cb6-71" aria-hidden="true" tabindex="-1"></a>        frameon<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb6-72"><a href="#cb6-72" aria-hidden="true" tabindex="-1"></a>        framealpha<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb6-73"><a href="#cb6-73" aria-hidden="true" tabindex="-1"></a>        edgecolor<span class="op">=</span><span class="st">"white"</span>,</span>
<span id="cb6-74"><a href="#cb6-74" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-75"><a href="#cb6-75" aria-hidden="true" tabindex="-1"></a>    leg.set_title(</span>
<span id="cb6-76"><a href="#cb6-76" aria-hidden="true" tabindex="-1"></a>        leg_title, prop<span class="op">=</span>{<span class="st">"size"</span>: <span class="dv">10</span>, <span class="st">"weight"</span>: <span class="st">"bold"</span>, <span class="st">"family"</span>: <span class="st">"sans-serif"</span>}</span>
<span id="cb6-77"><a href="#cb6-77" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-78"><a href="#cb6-78" aria-hidden="true" tabindex="-1"></a>    leg._legend_box.align <span class="op">=</span> <span class="st">"left"</span></span>
<span id="cb6-79"><a href="#cb6-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-80"><a href="#cb6-80" aria-hidden="true" tabindex="-1"></a>    plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="gender" class="level2">
<h2 class="anchored" data-anchor-id="gender">Gender</h2>
<p>Now we have these functions to make the plots we need, we can first take a look at the distribution of gender through time.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:13.517104Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:13.312963Z&quot;}" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>gender_df <span class="op">=</span> pd.pivot_table(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    castaways_df, columns<span class="op">=</span><span class="st">"gender"</span>, index<span class="op">=</span><span class="st">"year"</span>, values<span class="op">=</span><span class="st">"date"</span>, aggfunc<span class="op">=</span><span class="st">"count"</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>gender_df <span class="op">=</span> normalize_rows(gender_df)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>gender_df <span class="op">=</span> gender_df[[<span class="st">"male"</span>, <span class="st">"female"</span>]]</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>gender_df <span class="op">=</span> cumulative_columns(gender_df)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>make_timeplot(gender_df, horiz_line_y<span class="op">=</span><span class="fl">0.5</span>, leg_title<span class="op">=</span><span class="st">"Gender"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-03-09-Desert-Island-Discs_files/figure-html/cell-7-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Okay, there are a few things to notice here. The first is that, throughout the bulk of the show’s long history, there have been significantly more male castaways than female. But the plot is very spikey, demonstrating that from year to year the gender ratio of castaways on the show fluctuates by an appreciable amount. Since we are interested in looking at trends over several years, and not differences between consecutive years, lets try smoothing this plot by using a <a href="https://en.wikipedia.org/wiki/Moving_average">moving average</a> of 5 years.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:13.704186Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:13.519255Z&quot;}" data-execution_count="7">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>make_timeplot(moving_average(gender_df, n<span class="op">=</span><span class="dv">5</span>), horiz_line_y<span class="op">=</span><span class="fl">0.5</span>, leg_title<span class="op">=</span><span class="st">"Gender"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-03-09-Desert-Island-Discs_files/figure-html/cell-8-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The smoothed plot confirms the observation that the show has had significantly more males than females.</p>
<p>Around 1950, it looks as though there was a much more equal split between men and women. However, this conclusion is drawn a bit hurriedly. If we look at the number of episodes per year around this time, we see that the show was actually off the air for several years around this period. There was also a year (1946), where only one episode aired, and the castaway was female (actress <a href="https://www.bbc.co.uk/programmes/p009y00q">Barbara Mullen</a>). As we are giving each year equal visual weight with our plot, the show looks more balanced in terms of gender at it’s inception than it was.</p>
<p>From the beginning of the show, up until the early 2010s, there were about 3/4 male castaways and 1/4 female castaways. A little after 2010, we see a qualitative shift, and the split between males and females quickly becomes much more even. The suddenness of this change suggests it was a active decision taken by the producers of the show. The fact that this happened relatively recently is perhaps surprising.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:13.714778Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:13.707888Z&quot;}" data-execution_count="8">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Percentages of different genders, integrated over time"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="bu">round</span>(castaways_df[<span class="st">"gender"</span>].value_counts(dropna<span class="op">=</span><span class="va">False</span>) <span class="op">/</span> <span class="bu">len</span>(castaways_df) <span class="op">*</span> <span class="dv">100</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Percentages of different genders, integrated over time</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>male                  68.6
female                29.7
NaN                    1.6
transgender female     0.1
Name: gender, dtype: float64</code></pre>
</div>
</div>
<p>Finally, it’s worth noting that since Wikipedia does not have information on every castaway, we are missing information on some castaways. In this case, we don’t have a gender for 1.6% of castaways.</p>
</section>
<section id="age" class="level2">
<h2 class="anchored" data-anchor-id="age">Age</h2>
<p>We might also wonder whether the age of castaways (at the time of them appearing on the show) has changed over time. For example, might recent guests on the show be younger to appeal to a younger demographic of listeners?</p>
<p>Using the date of birth of the castaway from Wikidata, and the broadcast date of the episode, we can calculate how old the castaways were when they were on the show.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:13.738092Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:13.717434Z&quot;}" data-execution_count="9">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Age</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>cols_of_interest <span class="op">=</span> [<span class="st">"name"</span>, <span class="st">"std_name"</span>, <span class="st">"gender"</span>, <span class="st">"date"</span>, <span class="st">"date_of_birth"</span>, <span class="st">"year"</span>]</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>castaways_age_df <span class="op">=</span> castaways_df[cols_of_interest].assign(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    age<span class="op">=</span><span class="kw">lambda</span> x: (</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>        (x[<span class="st">"date"</span>].dt.year <span class="op">-</span> pd.to_datetime(castaways_df[<span class="st">"date_of_birth"</span>]).dt.year)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>        <span class="op">-</span> (x[<span class="st">"date"</span>].dt.month <span class="op">&lt;</span> pd.to_datetime(castaways_df[<span class="st">"date_of_birth"</span>]).dt.month)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>castaways_age_df.head(<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">std_name</th>
<th data-quarto-table-cell-role="th">gender</th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">date_of_birth</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Vic Oliver</td>
<td>vic oliver</td>
<td>male</td>
<td>1942-01-29</td>
<td>1898-07-08</td>
<td>1942</td>
<td>43.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:13.751113Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:13.740524Z&quot;}" data-execution_count="10">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find oldest castaway(s)</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>castaways_age_df.loc[castaways_age_df[<span class="st">"age"</span>] <span class="op">==</span> castaways_age_df[<span class="st">"age"</span>].<span class="bu">max</span>()]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">std_name</th>
<th data-quarto-table-cell-role="th">gender</th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">date_of_birth</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1455</td>
<td>Sir Robert Mayer</td>
<td>robert mayer</td>
<td>male</td>
<td>1979-06-05</td>
<td>1879-06-05</td>
<td>1979</td>
<td>100.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2258</td>
<td>Kathleen Hale</td>
<td>kathleen hale</td>
<td>female</td>
<td>1998-06-05</td>
<td>1898-05-24</td>
<td>1998</td>
<td>100.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:13.763159Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:13.753085Z&quot;}" data-execution_count="11">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find youngest castaway(s)</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>castaways_age_df.loc[castaways_age_df[<span class="st">"age"</span>] <span class="op">==</span> castaways_age_df[<span class="st">"age"</span>].<span class="bu">min</span>()]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">std_name</th>
<th data-quarto-table-cell-role="th">gender</th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">date_of_birth</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1024</td>
<td>Quentin Poole</td>
<td>quentin poole</td>
<td>male</td>
<td>1970-12-28</td>
<td>1957-01-01</td>
<td>1970</td>
<td>13.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The youngest castaway was musician <a href="https://www.bbc.co.uk/programmes/p009ndfl">Quentin Poole</a>, who at the age of 13 appeared on the 1970 Christmas episode when he was the head chorister at King’s College Cambridge. Businessman, philanthropist and patron of music <a href="https://www.bbc.co.uk/programmes/p009mxdk">Sir Robert Mayer</a> appeared on the programme on his 100th birthday.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:13.775905Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:13.765736Z&quot;}" data-execution_count="12">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make a dataframe of all teenagers</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>teens <span class="op">=</span> castaways_age_df[castaways_age_df[<span class="st">"age"</span>] <span class="op">&lt;</span> <span class="dv">20</span>]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>teens.head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">std_name</th>
<th data-quarto-table-cell-role="th">gender</th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">date_of_birth</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">84</td>
<td>Petula Clark</td>
<td>petula clark</td>
<td>female</td>
<td>1951-05-02</td>
<td>1932-11-15</td>
<td>1951</td>
<td>18.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">313</td>
<td>Janette Scott</td>
<td>janette scott</td>
<td>female</td>
<td>1956-12-24</td>
<td>1938-12-14</td>
<td>1956</td>
<td>18.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">736</td>
<td>Hayley Mills</td>
<td>hayley mills</td>
<td>female</td>
<td>1965-05-10</td>
<td>1946-04-18</td>
<td>1965</td>
<td>19.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1024</td>
<td>Quentin Poole</td>
<td>quentin poole</td>
<td>male</td>
<td>1970-12-28</td>
<td>1957-01-01</td>
<td>1970</td>
<td>13.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:13.790124Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:13.777581Z&quot;}" data-execution_count="13">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># and one of all those over 95 years old</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>older <span class="op">=</span> castaways_age_df[castaways_age_df[<span class="st">"age"</span>] <span class="op">&gt;</span> <span class="dv">95</span>]</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>older.head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">std_name</th>
<th data-quarto-table-cell-role="th">gender</th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">date_of_birth</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1455</td>
<td>Sir Robert Mayer</td>
<td>robert mayer</td>
<td>male</td>
<td>1979-06-05</td>
<td>1879-06-05</td>
<td>1979</td>
<td>100.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1497</td>
<td>Commissioner Catherine Bramwell-Booth</td>
<td>commissioner catherine bramwell-booth</td>
<td>female</td>
<td>1980-04-11</td>
<td>1883-07-20</td>
<td>1980</td>
<td>96.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1712</td>
<td>George Abbott</td>
<td>george abbott</td>
<td>male</td>
<td>1984-09-07</td>
<td>1887-06-25</td>
<td>1984</td>
<td>97.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1885</td>
<td>Athene Seyler</td>
<td>athene seyler</td>
<td>female</td>
<td>1989-03-19</td>
<td>1889-05-31</td>
<td>1989</td>
<td>99.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1903</td>
<td>Gwen Ffrangcon-Davies</td>
<td>gwen ffrangcon-davies</td>
<td>female</td>
<td>1989-09-01</td>
<td>1891-01-25</td>
<td>1989</td>
<td>98.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2258</td>
<td>Kathleen Hale</td>
<td>kathleen hale</td>
<td>female</td>
<td>1998-06-05</td>
<td>1898-05-24</td>
<td>1998</td>
<td>100.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2889</td>
<td>Jeremy Hutchinson</td>
<td>jeremy hutchinson</td>
<td>male</td>
<td>2013-10-25</td>
<td>1915-03-28</td>
<td>2013</td>
<td>98.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2961</td>
<td>Harry Rabinowitz</td>
<td>harry rabinowitz</td>
<td>male</td>
<td>2015-07-03</td>
<td>1916-03-26</td>
<td>2015</td>
<td>99.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>From the two dataframes, teens and older, we can see there have been 4 castaways under the age of 20, and 8 over the age of 95. There have been no teenaged castaways for over 51 years, and the last castaway over 95 was broadcast seven years ago.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:13.800160Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:13.792200Z&quot;}" data-execution_count="14">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate average age of male and female castaways</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>av_age_m <span class="op">=</span> castaways_age_df[castaways_age_df[<span class="st">"gender"</span>] <span class="op">==</span> <span class="st">"male"</span>][<span class="st">"age"</span>].mean()</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>av_age_f <span class="op">=</span> castaways_age_df[castaways_age_df[<span class="st">"gender"</span>] <span class="op">==</span> <span class="st">"female"</span>][<span class="st">"age"</span>].mean()</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"The average age of the male castaways is </span><span class="sc">{</span>av_age_m<span class="sc">:.1f}</span><span class="ss"> and the average age of the female castaways is </span><span class="sc">{</span>av_age_f<span class="sc">:.1f}</span><span class="ss">"</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The average age of the male castaways is 53.5 and the average age of the female castaways is 53.7</code></pre>
</div>
</div>
<p>A quick calculation shows that the average age for male and female castaways is very similar, around 53 and a half years old.</p>
<p>We now will segment the castaways by decade to explore trends in age over time.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:13.807481Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:13.802327Z&quot;}" data-execution_count="15">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add function to add median line to kde ridge plots</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> kdeplot_med(data, <span class="op">**</span>kwargs):</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> data.dropna(subset<span class="op">=</span>[kwargs[<span class="st">"x"</span>]])</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    _ax <span class="op">=</span> plt.gca()</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    density <span class="op">=</span> stats.gaussian_kde(data[kwargs[<span class="st">"x"</span>]].dropna())</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    _, ymax <span class="op">=</span> _ax.get_ybound()</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    _ax.axvline(</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>        data[kwargs[<span class="st">"x"</span>]].median(),</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>kwargs[<span class="st">"color"</span>],</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>        ymax<span class="op">=</span>(density(data[kwargs[<span class="st">"x"</span>]].median())[<span class="dv">0</span>] <span class="op">/</span> ymax),</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>    _ax.annotate(</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>        <span class="bu">int</span>(data[kwargs[<span class="st">"x"</span>]].median()),</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>        (data[kwargs[<span class="st">"x"</span>]].median() <span class="op">+</span> <span class="dv">1</span>, density(data[kwargs[<span class="st">"x"</span>]].median())[<span class="dv">0</span>] <span class="op">*</span> <span class="fl">0.65</span>),</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>        xycoords<span class="op">=</span><span class="st">"data"</span>,</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>        fontweight<span class="op">=</span><span class="st">"bold"</span>,</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> _ax</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:15.696145Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:13.809831Z&quot;}" data-execution_count="16">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"white"</span>, rc<span class="op">=</span>{<span class="st">"axes.facecolor"</span>: (<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)})</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> sns.FacetGrid(</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    castaways_age_df.assign(decade<span class="op">=</span><span class="kw">lambda</span> x: (x[<span class="st">"year"</span>] <span class="op">//</span> <span class="dv">10</span>) <span class="op">*</span> <span class="dv">10</span>),</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    palette<span class="op">=</span><span class="st">"Paired"</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    hue<span class="op">=</span><span class="st">"decade"</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    row<span class="op">=</span><span class="st">"decade"</span>,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    aspect<span class="op">=</span><span class="dv">7</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    height<span class="op">=</span><span class="fl">1.0</span>,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>BW <span class="op">=</span> <span class="fl">0.9</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>g.map_dataframe(</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    sns.kdeplot,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">"age"</span>,</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>    fill<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    bw_adjust<span class="op">=</span>BW,</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    clip_on<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>g.map_dataframe(sns.kdeplot, x<span class="op">=</span><span class="st">"age"</span>, color<span class="op">=</span><span class="st">"black"</span>, bw_adjust<span class="op">=</span>BW)</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>g.map_dataframe(</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>    kdeplot_med, x<span class="op">=</span><span class="st">"age"</span>, fill<span class="op">=</span><span class="va">True</span>, alpha<span class="op">=</span><span class="dv">1</span>, bw_adjust<span class="op">=</span>BW, clip_on<span class="op">=</span><span class="va">False</span>, color<span class="op">=</span><span class="st">"black"</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> label1(k, color, label):</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> plt.gca()</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>    ax.text(</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>        <span class="dv">0</span>,</span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>        <span class="fl">0.2</span>,</span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>        label <span class="op">+</span> <span class="st">"s"</span>,</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>        fontweight<span class="op">=</span><span class="st">"bold"</span>,</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">"black"</span>,</span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a>        ha<span class="op">=</span><span class="st">"left"</span>,</span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a>        va<span class="op">=</span><span class="st">"center"</span>,</span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a>        transform<span class="op">=</span>ax.transAxes,</span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a>g.<span class="bu">map</span>(label1, <span class="st">"age"</span>)</span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a>g.set_ylabels(<span class="st">""</span>)</span>
<span id="cb20-41"><a href="#cb20-41" aria-hidden="true" tabindex="-1"></a>g.set_xlabels(<span class="st">"Age"</span>)</span>
<span id="cb20-42"><a href="#cb20-42" aria-hidden="true" tabindex="-1"></a>g.fig.subplots_adjust(hspace<span class="op">=-</span><span class="fl">0.5</span>)</span>
<span id="cb20-43"><a href="#cb20-43" aria-hidden="true" tabindex="-1"></a>g.set_titles(<span class="st">""</span>)</span>
<span id="cb20-44"><a href="#cb20-44" aria-hidden="true" tabindex="-1"></a>g.<span class="bu">set</span>(yticks<span class="op">=</span>[])</span>
<span id="cb20-45"><a href="#cb20-45" aria-hidden="true" tabindex="-1"></a>g.despine(left<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb20-46"><a href="#cb20-46" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-03-09-Desert-Island-Discs_files/figure-html/cell-17-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Looking at the range of ages by decade, the plot above indicates that the castaways are aging over time: the media age has increased from the early 40s in the 1940s to late 50s in the 2020s. For comparison, the <a href="https://ourworldindata.org/grapher/median-age?tab=chart&amp;country=~GBR">median age of the British population</a> increased from 34.9 in 1950 to 40.2 in 2015.</p>
<p>A great example of how the guests (and audience?) are aging is castaway Sir Cliff Richard. The pop singer <a href="https://www.bbc.co.uk/programmes/p009y6z4">first appeared</a> on the show at the age of 20 in 1960 (favourite song: Rock Around the Clock by Bill Haley and his Comets, book: The Swiss Family Robinson by Johann Wyss, luxury: guitar) and returned for the 2020 <a href="https://www.bbc.co.uk/programmes/m000qhg8">Christmas epsiode</a> at the age of 80 (favourite song: It Is Well by Sheila Walsh featuring Cliff Richard, book: Wuthering Heights by Emily Brontë, luxury: a Gibson acoustic guitar).</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:15.720530Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:15.698405Z&quot;}" data-execution_count="17">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>castaways_df.query(<span class="st">"std_name == 'cliff richard'"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">episode_ref</th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">castaway_ref</th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">std_name</th>
<th data-quarto-table-cell-role="th">gender</th>
<th data-quarto-table-cell-role="th">profession</th>
<th data-quarto-table-cell-role="th">country_of_citizenship</th>
<th data-quarto-table-cell-role="th">place_of_birth</th>
<th data-quarto-table-cell-role="th">country_of_birth</th>
<th data-quarto-table-cell-role="th">date_of_birth</th>
<th data-quarto-table-cell-role="th">favTrack</th>
<th data-quarto-table-cell-role="th">luxury</th>
<th data-quarto-table-cell-role="th">book</th>
<th data-quarto-table-cell-role="th">wiki_link</th>
<th data-quarto-table-cell-role="th">link</th>
<th data-quarto-table-cell-role="th">year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">511</td>
<td>2654</td>
<td>1960-10-31</td>
<td>484</td>
<td>Cliff Richard</td>
<td>cliff richard</td>
<td>male</td>
<td>['film actor', 'actor', 'performing artist', '...</td>
<td>United Kingdom</td>
<td>Lucknow</td>
<td>India</td>
<td>1940-10-14</td>
<td>Rock Around The Clock by Bill Haley and His Co...</td>
<td>Guitar</td>
<td>The Swiss Family Robinson - Johann Wyss</td>
<td>https://en.wikipedia.org/wiki/Cliff_Richard</td>
<td>https://www.bbc.co.uk/programmes/p009y6z4</td>
<td>1960</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3190</td>
<td>3259</td>
<td>2020-12-20</td>
<td>484</td>
<td>Sir Cliff Richard</td>
<td>cliff richard</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaT</td>
<td>NaN</td>
<td>Wuthering Heights¬†by¬†Emily Bront√´</td>
<td>A Gibson¬†acoustic guitar</td>
<td>https://en.wikipedia.org/wiki/Sir_Cliff_Richard</td>
<td>https://www.bbc.co.uk/programmes/m000qhg8</td>
<td>2020</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="country-of-birth" class="level2">
<h2 class="anchored" data-anchor-id="country-of-birth">Country of birth</h2>
<p>From Wikipedia, we can also ask for information about the country of birth for the castaways on the show. For visual clarity, we have used the <code>pycountry</code> package to get the continent of each country, breaking the United Kingdom out into its own category due to the majority of castaways being born in the UK. This information is not always available, as reflected by the “other” category on the plot.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:02:15.727269Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:15.722911Z&quot;}" data-execution_count="18">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_continent(country):</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Fuzzy search for Continent based on input country, treating GB separately</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># first search for country</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>        code <span class="op">=</span> pc.countries.search_fuzzy(country)[<span class="dv">0</span>].alpha_2</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span>:</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>        code <span class="op">=</span> <span class="st">""</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> code <span class="op">==</span> <span class="st">""</span>:</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"Unknown"</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> code <span class="op">==</span> <span class="st">"GB"</span>:</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"UK"</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># next get continent code from country code</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>    continent_code <span class="op">=</span> pcc.country_alpha2_to_continent_code(code)</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> continent_code</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:04:27.577069Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:02:15.729095Z&quot;}" data-execution_count="19">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>castaways_df[<span class="st">"continent_of_birth"</span>] <span class="op">=</span> castaways_df.country_of_birth.<span class="bu">apply</span>(get_continent)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>birth_df <span class="op">=</span> pd.pivot_table(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    castaways_df,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span><span class="st">"continent_of_birth"</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    index<span class="op">=</span><span class="st">"year"</span>,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    values<span class="op">=</span><span class="st">"date"</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    aggfunc<span class="op">=</span><span class="st">"count"</span>,</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>birth_df <span class="op">=</span> normalize_rows(birth_df)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>birth_df <span class="op">=</span> birth_df[[<span class="st">"UK"</span>, <span class="st">"EU"</span>, <span class="st">"NA"</span>, <span class="st">"AF"</span>, <span class="st">"AS"</span>, <span class="st">"SA"</span>, <span class="st">"OC"</span>, <span class="st">"Unknown"</span>]]</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>birth_df <span class="op">=</span> cumulative_columns(birth_df)</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>make_timeplot(moving_average(birth_df, n<span class="op">=</span><span class="dv">5</span>), ymin<span class="op">=</span><span class="fl">0.0</span>, leg_title<span class="op">=</span><span class="st">"Country of Birth"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-03-09-Desert-Island-Discs_files/figure-html/cell-20-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Looking as a function of time, there are no drastic changes in the country of birth of castaways on the show. The fraction of castaways who have this information missing seems to have been slightly reduced since the beginning of the show. This could reflect changes in the notability of guests, or perhaps the increasing prevalence of information on Wikipedia.</p>
<p>For a BBC radio programme, perhaps it isn’t a surprise that most castaways are from the UK, with other English-speaking countries with cultural connections (Australia, USA) being very prominent. In fact, the large number of castaways from the USA from the start of the show might make sense in the context of castaway profession.</p>
</section>
<section id="profession" class="level2">
<h2 class="anchored" data-anchor-id="profession">Profession</h2>
<p>We can also ask Wikipedia for information about professions that the castaways have, in order to get a better idea of which roles in society are reflected on the show.</p>
<p>We obtain from Wikipedia a list of professions of decreasing granularity for each castaway. As such, the data isn’t all comparable without some initial work. For example, Vic Oliver is at the highest level of granularity an actor (as far as Wikipedia is concerned), but he is also a performing artist, an artist, and ultimately a professional.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:04:27.583266Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:04:27.578713Z&quot;}" data-execution_count="20">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>castaways_df.std_name.iloc[<span class="dv">0</span>], castaways_df.profession.iloc[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>('vic oliver', "['actor', 'performing artist', 'artist', 'professional']")</code></pre>
</div>
</div>
<p>Since the number of possible professions that Wikipedia has knowledge of is too large to easily digest in a plot, we need to group similar professions into broad enough categories for visualisation. Do do this, we next define some functions to cluster professions, aiming to have the most granular profession for each castaway, while still maintaining a manageable number of possible categories. These functions are a little ad hoc, and rely on some parameters that have been manually selected to achieve sensible results. A more sophisticated approach could reduce the need for this.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:04:27.591476Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:04:27.585487Z&quot;}" data-execution_count="21">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> <span class="bu">reduce</span>(prof_list, common_professions):</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Given a list of professions for a single castaway, try and return the most</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co">    granular profession for this castaway if it is common enough.</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># no options available, just take whatever profession is left</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(prof_list) <span class="op">==</span> <span class="dv">1</span> <span class="kw">or</span> <span class="st">"professional"</span> <span class="kw">in</span> prof_list[<span class="dv">1</span>]:</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> [prof_list[<span class="dv">0</span>]]</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># take the most granular profession if it is common</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> prof <span class="kw">in</span> prof_list:</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> prof <span class="kw">in</span> common_professions <span class="kw">and</span> prof <span class="op">!=</span> <span class="st">"professional"</span>:</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> [prof]</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># if none are common, restrict the set of professions to cluster</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> prof_list[<span class="dv">1</span>:]</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cluster_step(profession_lists, n<span class="op">=</span><span class="dv">10</span>):</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a><span class="co">    At each step, take the n most common professions that appear globally,</span></span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a><span class="co">    and attempt to match castaways to one of these professions.</span></span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># get the most common categories</span></span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a>    common_professions <span class="op">=</span> pd.Series(</span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a>        [i <span class="cf">for</span> x <span class="kw">in</span> profession_lists <span class="cf">for</span> i <span class="kw">in</span> x]</span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a>    ).value_counts()[:n]</span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a>    <span class="co"># apply clustering</span></span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a>    out <span class="op">=</span> [<span class="bu">reduce</span>(p, common_professions) <span class="cf">for</span> p <span class="kw">in</span> profession_lists]</span>
<span id="cb26-34"><a href="#cb26-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-35"><a href="#cb26-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> out</span>
<span id="cb26-36"><a href="#cb26-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-37"><a href="#cb26-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-38"><a href="#cb26-38" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> simplify_professions(profession_lists, n<span class="op">=</span><span class="dv">25</span>):</span>
<span id="cb26-39"><a href="#cb26-39" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb26-40"><a href="#cb26-40" aria-hidden="true" tabindex="-1"></a><span class="co">    Run the clustering process.</span></span>
<span id="cb26-41"><a href="#cb26-41" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb26-42"><a href="#cb26-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-43"><a href="#cb26-43" aria-hidden="true" tabindex="-1"></a>    <span class="co"># run clustering iteratively for ten steps</span></span>
<span id="cb26-44"><a href="#cb26-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10</span>):</span>
<span id="cb26-45"><a href="#cb26-45" aria-hidden="true" tabindex="-1"></a>        profession_lists <span class="op">=</span> cluster_step(profession_lists)</span>
<span id="cb26-46"><a href="#cb26-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-47"><a href="#cb26-47" aria-hidden="true" tabindex="-1"></a>    <span class="co"># clean</span></span>
<span id="cb26-48"><a href="#cb26-48" aria-hidden="true" tabindex="-1"></a>    professions <span class="op">=</span> [p[<span class="dv">0</span>] <span class="cf">for</span> p <span class="kw">in</span> profession_lists]</span>
<span id="cb26-49"><a href="#cb26-49" aria-hidden="true" tabindex="-1"></a>    least_common <span class="op">=</span> pd.Series(professions).value_counts(ascending<span class="op">=</span><span class="va">True</span>)[:n]</span>
<span id="cb26-50"><a href="#cb26-50" aria-hidden="true" tabindex="-1"></a>    professions <span class="op">=</span> [p <span class="cf">if</span> p <span class="kw">not</span> <span class="kw">in</span> least_common <span class="cf">else</span> <span class="st">"other"</span> <span class="cf">for</span> p <span class="kw">in</span> professions]</span>
<span id="cb26-51"><a href="#cb26-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-52"><a href="#cb26-52" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> professions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we have the clustering functions defined, we can define one additional function which does some preprocessing, runs the clustering, and makes a plot.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:04:27.598399Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:04:27.593386Z&quot;}" data-execution_count="22">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_profession_plot(df, n<span class="op">=</span><span class="dv">20</span>, window<span class="op">=</span><span class="dv">10</span>, leg_title<span class="op">=</span><span class="st">""</span>):</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    profession_df <span class="op">=</span> df.copy()</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    profession_df.loc[profession_df.profession <span class="op">==</span> <span class="st">"[]"</span>, <span class="st">"profession"</span>] <span class="op">=</span> np.nan</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    profession_df <span class="op">=</span> profession_df.fillna({<span class="st">"profession"</span>: <span class="st">"['unknown']"</span>})</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    profession_df.profession <span class="op">=</span> profession_df.profession.<span class="bu">apply</span>(</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>        <span class="kw">lambda</span> x: ast.literal_eval(x)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    profession_df[<span class="st">"profession"</span>] <span class="op">=</span> simplify_professions(profession_df[<span class="st">"profession"</span>], n<span class="op">=</span>n)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>    prof_df <span class="op">=</span> pd.pivot_table(</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>        profession_df,</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>        columns<span class="op">=</span><span class="st">"profession"</span>,</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>        index<span class="op">=</span><span class="st">"year"</span>,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>        values<span class="op">=</span><span class="st">"date"</span>,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>        aggfunc<span class="op">=</span><span class="st">"count"</span>,</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>    prof_df <span class="op">=</span> prof_df[</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>        [c <span class="cf">for</span> c <span class="kw">in</span> prof_df.columns <span class="cf">if</span> c <span class="kw">not</span> <span class="kw">in</span> [<span class="st">"other"</span>, <span class="st">"unknown"</span>]]</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span> [<span class="st">"other"</span>, <span class="st">"unknown"</span>]</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>    prof_df <span class="op">=</span> normalize_rows(prof_df)</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>    prof_df <span class="op">=</span> cumulative_columns(prof_df)</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>    make_timeplot(moving_average(prof_df, n<span class="op">=</span>window), ymin<span class="op">=</span><span class="fl">0.0</span>, leg_title<span class="op">=</span>leg_title)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:04:27.946124Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:04:27.604271Z&quot;}" data-execution_count="23">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>get_profession_plot(castaways_df, n<span class="op">=</span><span class="dv">34</span>, leg_title<span class="op">=</span><span class="st">"Profession"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-03-09-Desert-Island-Discs_files/figure-html/cell-24-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>As you can see, the professions most frequently represented on Desert Island Discs are people who work in the media and creative industries – actors, artists, journalists, musicians and writers. This makes sense, as it is an entertainment programme with a foundation of music. But we were surprised not to see more representation from the many professions that are influential in British society - politicians, athletes, academics and people involved in business, health, and law are all very small percentages of castaways.</p>
<p>There are also clear trends visible over time. In the first half of the show’s history actors and musicians made up the bulk of guests. In more recent years the proportion of castaways being grouped into the “other” category has increased, indicating an increase diversity in castaways’ occupations.</p>
</section>
</section>
<section id="discs" class="level1">
<h1>Discs</h1>
<p>In the dataset we introduced in the beginning, we also grabbed information about the songs shared by each castaway. Based on Andrew’s initial analysis, we know that classical music dominates the musical selections, and we want to dig a little deeper into the types of music chosen over time, as well what types of people choose different genres building on the analysis above.</p>
<section id="genres" class="level2">
<h2 class="anchored" data-anchor-id="genres">Genres</h2>
<p>From Spotify, we can get a list of genres associated with the musical artist and additional info and analysis for each song (for example, danceability). It turns out Spotify has an overwhelming number of microgenres – see Glenn McDonald’s <a href="https://everynoise.com">everynoise.com</a> for a mind blowing micro-genre experience – and we need to do some work to get a small number of the most common and most easily recognised genres. We initial had hoped to algorithmically develop a series of meta-genres to use for analysis, but this proved beyond the scope of this data story.</p>
<p>To start, we can load the discs data, and the dataset pulled from Spotify API. These are then merged.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:03.145416Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:04:27.950105Z&quot;}" data-execution_count="24">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load discs data</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>discs_df <span class="op">=</span> pd.read_excel(</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    hc_data_url, sheet_name<span class="op">=</span><span class="st">"discs"</span>, parse_dates<span class="op">=</span>[<span class="st">"date"</span>], index_col<span class="op">=</span><span class="dv">0</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co"># load spotify data</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>spotify_df <span class="op">=</span> pd.read_excel(</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>    hc_data_url, sheet_name<span class="op">=</span><span class="st">"spotify_data"</span>, parse_dates<span class="op">=</span>[<span class="st">"date"</span>], index_col<span class="op">=</span><span class="dv">0</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>spotify_df.genres_artist <span class="op">=</span> spotify_df.genres_artist.<span class="bu">apply</span>(<span class="kw">lambda</span> x: ast.literal_eval(x))</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>spotify_df <span class="op">=</span> spotify_df.dropna(subset<span class="op">=</span>[<span class="st">"track"</span>])</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co"># combine disks and spotify data</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>merged_df <span class="op">=</span> pd.merge(</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>    discs_df,</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>    spotify_df,</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>    left_on<span class="op">=</span>[<span class="st">"track_name"</span>, <span class="st">"date"</span>],</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>    right_on<span class="op">=</span>[<span class="st">"track_name_original"</span>, <span class="st">"date"</span>],</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>    how<span class="op">=</span><span class="st">"inner"</span>,</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a><span class="co"># extract year</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>merged_df[<span class="st">"year"</span>] <span class="op">=</span> merged_df[<span class="st">"date"</span>].dt.year</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now the interesting part. After a bit of a manual look through the most common microgenres returned by Spotify, we came up with the following manual grouping.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:03.157780Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:03.147605Z&quot;}" data-execution_count="25">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>meta_genres <span class="op">=</span> {</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"pop"</span>: [<span class="st">"easy listening"</span>],</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"rock"</span>: [],</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"folk"</span>: [</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">"bothy"</span>,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"celtic"</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">"scottish"</span>,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">"bagpipe"</span>,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"irish"</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">"welsh"</span>,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">"bluegrass"</span>,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">"country"</span>,</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"jazz"</span>: [</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">"blues"</span>,</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">"british dance band"</span>,</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">"big band"</span>,</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>        <span class="st">"ragtime"</span>,</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">"boogie"</span>,</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>        <span class="st">"brass band"</span>,</span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"classical"</span>: [</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>        <span class="st">"choral"</span>,</span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>        <span class="st">"bolero"</span>,</span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>        <span class="st">"opera"</span>,</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>        <span class="st">"operetta"</span>,</span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>        <span class="st">"orchestral"</span>,</span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>        <span class="st">"orchestra"</span>,</span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>        <span class="st">"romantic era"</span>,</span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a>        <span class="st">"light music"</span>,</span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a>        <span class="st">"baroque"</span>,</span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">"vintage"</span>: [</span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a>        <span class="st">"adult standards"</span>,</span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a>        <span class="st">"music hall"</span>,</span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a>        <span class="st">"british comedy"</span>,</span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a>        <span class="st">"broadway"</span>,</span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a>        <span class="st">"cabaret"</span>,</span>
<span id="cb30-39"><a href="#cb30-39" aria-hidden="true" tabindex="-1"></a>        <span class="st">"tin pan alley"</span>,</span>
<span id="cb30-40"><a href="#cb30-40" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb30-41"><a href="#cb30-41" aria-hidden="true" tabindex="-1"></a>    <span class="st">"world"</span>: [</span>
<span id="cb30-42"><a href="#cb30-42" aria-hidden="true" tabindex="-1"></a>        <span class="st">"italian"</span>,</span>
<span id="cb30-43"><a href="#cb30-43" aria-hidden="true" tabindex="-1"></a>        <span class="st">"chanson"</span>,</span>
<span id="cb30-44"><a href="#cb30-44" aria-hidden="true" tabindex="-1"></a>        <span class="st">"french"</span>,</span>
<span id="cb30-45"><a href="#cb30-45" aria-hidden="true" tabindex="-1"></a>        <span class="st">"bossa"</span>,</span>
<span id="cb30-46"><a href="#cb30-46" aria-hidden="true" tabindex="-1"></a>        <span class="st">"samba"</span>,</span>
<span id="cb30-47"><a href="#cb30-47" aria-hidden="true" tabindex="-1"></a>        <span class="st">"flamenco"</span>,</span>
<span id="cb30-48"><a href="#cb30-48" aria-hidden="true" tabindex="-1"></a>        <span class="st">"salsa"</span>,</span>
<span id="cb30-49"><a href="#cb30-49" aria-hidden="true" tabindex="-1"></a>        <span class="st">"latin"</span>,</span>
<span id="cb30-50"><a href="#cb30-50" aria-hidden="true" tabindex="-1"></a>        <span class="st">"african"</span>,</span>
<span id="cb30-51"><a href="#cb30-51" aria-hidden="true" tabindex="-1"></a>        <span class="st">"zither"</span>,</span>
<span id="cb30-52"><a href="#cb30-52" aria-hidden="true" tabindex="-1"></a>        <span class="st">"cuban rumba"</span>,</span>
<span id="cb30-53"><a href="#cb30-53" aria-hidden="true" tabindex="-1"></a>        <span class="st">"arpa paraguaya"</span>,</span>
<span id="cb30-54"><a href="#cb30-54" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb30-55"><a href="#cb30-55" aria-hidden="true" tabindex="-1"></a>    <span class="st">"modern"</span>: [</span>
<span id="cb30-56"><a href="#cb30-56" aria-hidden="true" tabindex="-1"></a>        <span class="st">"disco"</span>,</span>
<span id="cb30-57"><a href="#cb30-57" aria-hidden="true" tabindex="-1"></a>        <span class="st">"soul"</span>,</span>
<span id="cb30-58"><a href="#cb30-58" aria-hidden="true" tabindex="-1"></a>        <span class="st">"r&amp;b"</span>,</span>
<span id="cb30-59"><a href="#cb30-59" aria-hidden="true" tabindex="-1"></a>        <span class="st">"reggae"</span>,</span>
<span id="cb30-60"><a href="#cb30-60" aria-hidden="true" tabindex="-1"></a>        <span class="st">"ska"</span>,</span>
<span id="cb30-61"><a href="#cb30-61" aria-hidden="true" tabindex="-1"></a>        <span class="st">"hip hop"</span>,</span>
<span id="cb30-62"><a href="#cb30-62" aria-hidden="true" tabindex="-1"></a>        <span class="st">"rap"</span>,</span>
<span id="cb30-63"><a href="#cb30-63" aria-hidden="true" tabindex="-1"></a>        <span class="st">"electronic"</span>,</span>
<span id="cb30-64"><a href="#cb30-64" aria-hidden="true" tabindex="-1"></a>        <span class="st">"electronica"</span>,</span>
<span id="cb30-65"><a href="#cb30-65" aria-hidden="true" tabindex="-1"></a>        <span class="st">"house"</span>,</span>
<span id="cb30-66"><a href="#cb30-66" aria-hidden="true" tabindex="-1"></a>        <span class="st">"ambient"</span>,</span>
<span id="cb30-67"><a href="#cb30-67" aria-hidden="true" tabindex="-1"></a>        <span class="st">"downtempo"</span>,</span>
<span id="cb30-68"><a href="#cb30-68" aria-hidden="true" tabindex="-1"></a>        <span class="st">"garage"</span>,</span>
<span id="cb30-69"><a href="#cb30-69" aria-hidden="true" tabindex="-1"></a>        <span class="st">"synthesizer"</span>,</span>
<span id="cb30-70"><a href="#cb30-70" aria-hidden="true" tabindex="-1"></a>        <span class="st">"drum and bass"</span>,</span>
<span id="cb30-71"><a href="#cb30-71" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb30-72"><a href="#cb30-72" aria-hidden="true" tabindex="-1"></a>    <span class="st">"spoken &amp; soundtrack"</span>: [</span>
<span id="cb30-73"><a href="#cb30-73" aria-hidden="true" tabindex="-1"></a>        <span class="st">"soundtrack"</span>,</span>
<span id="cb30-74"><a href="#cb30-74" aria-hidden="true" tabindex="-1"></a>        <span class="st">"hollywood"</span>,</span>
<span id="cb30-75"><a href="#cb30-75" aria-hidden="true" tabindex="-1"></a>        <span class="st">"show tunes"</span>,</span>
<span id="cb30-76"><a href="#cb30-76" aria-hidden="true" tabindex="-1"></a>        <span class="st">"movie"</span>,</span>
<span id="cb30-77"><a href="#cb30-77" aria-hidden="true" tabindex="-1"></a>        <span class="st">"poetry"</span>,</span>
<span id="cb30-78"><a href="#cb30-78" aria-hidden="true" tabindex="-1"></a>        <span class="st">"comic"</span>,</span>
<span id="cb30-79"><a href="#cb30-79" aria-hidden="true" tabindex="-1"></a>        <span class="st">"reading"</span>,</span>
<span id="cb30-80"><a href="#cb30-80" aria-hidden="true" tabindex="-1"></a>        <span class="st">"comedy"</span>,</span>
<span id="cb30-81"><a href="#cb30-81" aria-hidden="true" tabindex="-1"></a>        <span class="st">"oratory"</span>,</span>
<span id="cb30-82"><a href="#cb30-82" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb30-83"><a href="#cb30-83" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb30-84"><a href="#cb30-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-85"><a href="#cb30-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-86"><a href="#cb30-86" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> determine_genre(genre_list):</span>
<span id="cb30-87"><a href="#cb30-87" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb30-88"><a href="#cb30-88" aria-hidden="true" tabindex="-1"></a><span class="co">    Given a list of genres for a particular song, return the first</span></span>
<span id="cb30-89"><a href="#cb30-89" aria-hidden="true" tabindex="-1"></a><span class="co">    matched meta genre.</span></span>
<span id="cb30-90"><a href="#cb30-90" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb30-91"><a href="#cb30-91" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> genre_list <span class="op">==</span> []:</span>
<span id="cb30-92"><a href="#cb30-92" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">""</span></span>
<span id="cb30-93"><a href="#cb30-93" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> genre <span class="kw">in</span> genre_list:</span>
<span id="cb30-94"><a href="#cb30-94" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> meta_genre <span class="kw">in</span> meta_genres.keys():</span>
<span id="cb30-95"><a href="#cb30-95" aria-hidden="true" tabindex="-1"></a>            search_strings <span class="op">=</span> [meta_genre] <span class="op">+</span> meta_genres[meta_genre]</span>
<span id="cb30-96"><a href="#cb30-96" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="bu">any</span>([s <span class="kw">in</span> genre <span class="cf">for</span> s <span class="kw">in</span> search_strings]):</span>
<span id="cb30-97"><a href="#cb30-97" aria-hidden="true" tabindex="-1"></a>                <span class="cf">return</span> meta_genre</span>
<span id="cb30-98"><a href="#cb30-98" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">"other"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can use the groups of genres defined above to turn the list of genres associated with each track into a single metagenre. Anything not captured in our very coarse categorisation goes into the “other” metagenre.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:03.540453Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:03.160258Z&quot;}" data-execution_count="26">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get metagenre from the genre list</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>merged_df[<span class="st">"genre"</span>] <span class="op">=</span> merged_df.genres_artist.<span class="bu">apply</span>(determine_genre)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># drop rows without any genre</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>merged_df <span class="op">=</span> merged_df[merged_df[<span class="st">"genre"</span>] <span class="op">!=</span> <span class="st">""</span>].copy()</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co"># make a timeplot</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>genre_df <span class="op">=</span> pd.pivot_table(</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>    merged_df, columns<span class="op">=</span><span class="st">"genre"</span>, index<span class="op">=</span><span class="st">"year"</span>, values<span class="op">=</span><span class="st">"date"</span>, aggfunc<span class="op">=</span><span class="st">"count"</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>genre_df <span class="op">=</span> genre_df[[c <span class="cf">for</span> c <span class="kw">in</span> genre_df.columns <span class="cf">if</span> c <span class="kw">not</span> <span class="kw">in</span> [<span class="st">"other"</span>]] <span class="op">+</span> [<span class="st">"other"</span>]]</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>genre_df <span class="op">=</span> normalize_rows(genre_df)</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>genre_df <span class="op">=</span> cumulative_columns(genre_df)</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>make_timeplot(moving_average(genre_df, n<span class="op">=</span><span class="dv">5</span>), ymin<span class="op">=</span><span class="fl">0.0</span>, leg_title<span class="op">=</span><span class="st">"Genres"</span>, y_title<span class="op">=</span><span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-03-09-Desert-Island-Discs_files/figure-html/cell-27-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The plot above clearly illustrates the shift away from classical music, which doesn’t really start until Plomley’s reign as host ends in the mid-1980s. This trend accelerated after 2000 and rock music now represents a larger proportion of dics than classical music.</p>
<p>The “vintage” category was the second largest genre for much of the programme. Including artists like Frank Sinatra, it captures the popular music of the 1950s and now reflects more retro tastes. The “modern” category combines a number of more recent genres, from disco and ska to hip-hop and rap.</p>
<p>Next we see who were the most popular artists per year. First we merge our castaway and disc datasets, in order to have all the available information in one single dataframe.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:03.618187Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:03.542622Z&quot;}" data-execution_count="27">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>total_df <span class="op">=</span> pd.merge(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    merged_df,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    castaways_df,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    left_on<span class="op">=</span>[<span class="st">"std_name"</span>, <span class="st">"date"</span>, <span class="st">"episode_ref_x"</span>, <span class="st">"castaway_ref"</span>],</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    right_on<span class="op">=</span>[<span class="st">"std_name"</span>, <span class="st">"date"</span>, <span class="st">"episode_ref"</span>, <span class="st">"castaway_ref"</span>],</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    how<span class="op">=</span><span class="st">"inner"</span>,</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:04.086347Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:03.620456Z&quot;}" data-execution_count="28">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># choose only after 1950, before data looks weird given few entries and group by year</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>df1_grouped <span class="op">=</span> total_df[total_df[<span class="st">"year_x"</span>] <span class="op">&gt;</span> <span class="dv">1949</span>].groupby(<span class="st">"year_x"</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>dates <span class="op">=</span> []</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>levels <span class="op">=</span> []</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>names <span class="op">=</span> []</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> group_name, df_group <span class="kw">in</span> df1_grouped:</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># year</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>    dates.append(group_name)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># percentage of times it is chosen</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>    levels.append(</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>        df_group[<span class="st">"std_artist"</span>].value_counts()[:<span class="dv">1</span>].values[<span class="dv">0</span>]</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>        <span class="op">/</span> df_group[<span class="st">"std_artist"</span>].shape[<span class="dv">0</span>]</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># artist chosen (last name)</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>    names.append(df_group[<span class="st">"std_artist"</span>].value_counts()[:<span class="dv">1</span>].index[<span class="dv">0</span>].split(<span class="st">" "</span>)[<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a><span class="co"># associating names to colours and order them chronologically</span></span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a>names_cronological <span class="op">=</span> <span class="bu">list</span>(<span class="bu">dict</span>.fromkeys(names))</span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>c <span class="op">=</span> sns.color_palette(<span class="st">"Spectral"</span>, <span class="bu">max</span>(<span class="dv">4</span>, <span class="bu">len</span>(np.unique(names_cronological))))</span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a>colours <span class="op">=</span> {g: c[i] <span class="cf">for</span> i, g <span class="kw">in</span> <span class="bu">enumerate</span>(names_cronological)}</span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Create figure and bar plot</span></span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">5</span>))</span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Most popular artists by year"</span>, fontsize<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a>ax.bar(dates, levels, <span class="dv">1</span>, color<span class="op">=</span>[colours[x] <span class="cf">for</span> x <span class="kw">in</span> names])</span>
<span id="cb33-33"><a href="#cb33-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-34"><a href="#cb33-34" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> <span class="bu">list</span>(colours.keys())</span>
<span id="cb33-35"><a href="#cb33-35" aria-hidden="true" tabindex="-1"></a>handles <span class="op">=</span> [plt.Rectangle((<span class="dv">0</span>, <span class="dv">0</span>), <span class="dv">1</span>, <span class="dv">1</span>, color<span class="op">=</span>colours[x]) <span class="cf">for</span> x <span class="kw">in</span> names_cronological]</span>
<span id="cb33-36"><a href="#cb33-36" aria-hidden="true" tabindex="-1"></a>ax.legend(handles, labels, facecolor<span class="op">=</span><span class="st">"white"</span>, ncol<span class="op">=</span><span class="dv">2</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb33-37"><a href="#cb33-37" aria-hidden="true" tabindex="-1"></a>ax.grid(<span class="va">False</span>)</span>
<span id="cb33-38"><a href="#cb33-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-39"><a href="#cb33-39" aria-hidden="true" tabindex="-1"></a><span class="co"># remove y axis and spines</span></span>
<span id="cb33-40"><a href="#cb33-40" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Percentage of times chosen by Castaways"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb33-41"><a href="#cb33-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-42"><a href="#cb33-42" aria-hidden="true" tabindex="-1"></a>ax.margins(y<span class="op">=</span><span class="fl">0.1</span>)</span>
<span id="cb33-43"><a href="#cb33-43" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-03-09-Desert-Island-Discs_files/figure-html/cell-29-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The most popular artist by year parallels the overall look at genres. Classical composers dominate until the early 2000s, with a classical grudge match between Bach, Beethoven and Mozart. Over the past two decades, The Beatles consistently top the charts, joined by Frank Sinatra, Bob Marley, David Bowie, Joni Mitchell, and Nina Simone.</p>
</section>
</section>
<section id="castaways-and-discs" class="level1">
<h1>Castaways and discs</h1>
<p>We now will combine information about people and the music that they chose to look for any trends. Before getting into a more sophisticated network analysis, we can look at the musical genres chosen by different castaway professions.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:04.602166Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:04.088734Z&quot;}" data-execution_count="29">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>total_genpro_df <span class="op">=</span> total_df[[<span class="st">"profession"</span>, <span class="st">"genre"</span>]].copy()</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>total_genpro_df.loc[total_genpro_df.profession <span class="op">==</span> <span class="st">"[]"</span>, <span class="st">"profession"</span>] <span class="op">=</span> np.nan</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>total_genpro_df <span class="op">=</span> total_genpro_df.dropna()</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>total_genpro_df.profession <span class="op">=</span> total_genpro_df.profession.<span class="bu">apply</span>(</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">lambda</span> x: ast.literal_eval(x)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>total_genpro_df[<span class="st">"profession"</span>] <span class="op">=</span> simplify_professions(</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    total_genpro_df[<span class="st">"profession"</span>], n<span class="op">=</span><span class="dv">32</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>total_genpro_df <span class="op">=</span> total_genpro_df.sort_values(</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"profession"</span>, <span class="st">"genre"</span>], ascending<span class="op">=</span>[<span class="va">True</span>, <span class="va">False</span>]</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Move 'other' to be at the end.</span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>other_profession <span class="op">=</span> total_genpro_df[<span class="st">"profession"</span>] <span class="op">==</span> <span class="st">"other"</span></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>total_genpro_df <span class="op">=</span> pd.concat(</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>    (total_genpro_df[<span class="op">~</span>other_profession], total_genpro_df[other_profession])</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>other_genre <span class="op">=</span> total_genpro_df[<span class="st">"genre"</span>] <span class="op">==</span> <span class="st">"other"</span></span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>total_genpro_df <span class="op">=</span> pd.concat(</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>    (total_genpro_df[other_genre], total_genpro_df[<span class="op">~</span>other_genre])</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:05.247515Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:04.603757Z&quot;}" data-execution_count="30">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">5</span>))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> sns.histplot(</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>total_genpro_df, y<span class="op">=</span><span class="st">"profession"</span>, hue<span class="op">=</span><span class="st">"genre"</span>, multiple<span class="op">=</span><span class="st">"fill"</span>, palette<span class="op">=</span><span class="st">"Paired"</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>sns.move_legend(g, <span class="st">"upper left"</span>, bbox_to_anchor<span class="op">=</span>(<span class="dv">1</span>, <span class="dv">1</span>), frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>g.set_xlabel(<span class="st">"Fraction"</span>, fontsize<span class="op">=</span><span class="dv">18</span>)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>g.set_ylabel(<span class="st">"Profession"</span>, fontsize<span class="op">=</span><span class="dv">18</span>)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-03-09-Desert-Island-Discs_files/figure-html/cell-31-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Politicians have been accused of using focus groups to pick their discs, so we were curious about how they compared to other professions. The genre breakdown for politicians is broadly similar to the creative professions and other fields. Musicians and singers (including many which were classically trained) are more likely to pick classical music. For athletes and businesspeople, a larger proportion of genres are popular music (modern, pop, rock, vintage).</p>
<section id="network-analysis" class="level2">
<h2 class="anchored" data-anchor-id="network-analysis">Network analysis</h2>
<p>An interesting way of looking at this data is to think of it as a network. You can have two kind of networks: one where the castaways are the nodes and they are connected by having chosen the same musical artist, and the other one is where the musical artists are the nodes and their connections are defined by how many castaways chose them together.</p>
<p>A network analysis can give us an idea of castaway/artist similarity and popularity, as well as uncovering some non-trivial patterns (in the best of cases).</p>
<p>Let’s start building a network for our castaways. We will use our castaway and disc merged dataset, in order to have all the available information in one single dataframe.</p>
<p>Some of our castaways have appeared in more than one episode. Let’s check who:</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:09.794874Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:05.249380Z&quot;}" data-execution_count="31">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># if the is a person with more than one episode keep indexes of the last episode only,</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># given that our dataset is sorted we do this by only keeping the last entry</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>list_index <span class="op">=</span> []</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>count_repeats <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name <span class="kw">in</span> np.unique(total_df[[<span class="st">"std_name"</span>]]):</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>    castaway <span class="op">=</span> total_df[total_df[<span class="st">"std_name"</span>] <span class="op">==</span> name]</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>    dates <span class="op">=</span> np.unique(castaway[<span class="st">"date"</span>].values)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(dates) <span class="op">&gt;</span> <span class="dv">1</span>:</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>        count_repeats <span class="op">=</span> count_repeats <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="bu">len</span>(dates) <span class="op">&gt;</span> <span class="dv">3</span>:</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>            <span class="bu">print</span>(name, <span class="st">":"</span>, [<span class="bu">str</span>(d)[:<span class="dv">10</span>] <span class="cf">for</span> d <span class="kw">in</span> dates])</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># saving the index of the latest episode avalaible for each cast away</span></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>    index <span class="op">=</span> castaway[(castaway[<span class="st">"date"</span>] <span class="op">==</span> dates[<span class="op">-</span><span class="dv">1</span>])].index.values</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>    list_index <span class="op">=</span> [<span class="op">*</span>list_index, <span class="op">*</span>index]</span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a>    count_repeats,</span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">" recurrent guests out of"</span>,</span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>    <span class="bu">len</span>(np.unique(total_df[[<span class="st">"castaway_ref"</span>]])),</span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>arthur askey : ['1942-04-02', '1955-04-21', '1968-12-23', '1980-12-26']
david attenborough : ['1957-05-06', '1979-03-13', '1998-12-27', '2012-02-03']
202  recurrent guests out of 2450</code></pre>
</div>
</div>
<p>As you can see above, both David Attenborough and was Arthur Askey were invited to the show four times!</p>
<p>Having repeated guests in our dataset can be problematic for building the network, as these castaways will have more connections than the ones that have been invited only once. To resolve this problem, let’s make sure we only have one episode per castaway, by selecting the most recent episode available.</p>
<p>This count of total and repeat castaways is a little less than at the top of this notebook. As we are using a dataframe that has been merged with other data sources (Wikpedia, Spotify) we have lost some castaways where there was missing information. This is discussed in more detail in the conclusions.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:09.810156Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:09.796719Z&quot;}" data-execution_count="32">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select only one episode per cast away using the indexes stored above</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>df_network <span class="op">=</span> total_df.iloc[list_index]</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>df_network.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="32">
<pre><code>(12857, 53)</code></pre>
</div>
</div>
</section>
<section id="castaway-network" class="level2">
<h2 class="anchored" data-anchor-id="castaway-network">Castaway network</h2>
<p>Let’s now build the castaway network. For this we have written the function below: for each available pair of nodes (castaways in this case) it counts how many connections it has (common artists). This is typically called an edge list that defines a source and target (nodes), and it gives it a weight (edge).</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:09.817190Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:09.812124Z&quot;}" data-execution_count="33">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> build_network(df, nodes_variable, edges_variable):</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Function that builds a newtork based on given nodes or edges that are</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="co">    columns names on the input dataframe"""</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># loop over all the unique values of the edges columns</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    df_list <span class="op">=</span> []</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> edge <span class="kw">in</span> np.unique(df[edges_variable].astype(<span class="bu">str</span>).values):</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>        <span class="co"># get the all the nodes that have that edge</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>        nodes <span class="op">=</span> np.unique(</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>            df[df[edges_variable] <span class="op">==</span> edge][nodes_variable].dropna().values</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>        <span class="co"># get all combination of nodes existing for that edge</span></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>        <span class="co"># and save it to a list where source and</span></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>        <span class="co"># targes are the nodes conected by that edge</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="bu">len</span>(nodes) <span class="op">&gt;</span> <span class="dv">1</span>:</span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>            source, target <span class="op">=</span> <span class="bu">zip</span>(<span class="op">*</span>itertools.combinations(nodes, <span class="dv">2</span>))</span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a>            df_net <span class="op">=</span> pd.DataFrame()</span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>            df_net[<span class="st">"source"</span>] <span class="op">=</span> source</span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a>            df_net[<span class="st">"target"</span>] <span class="op">=</span> target</span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a>            df_list.append(df_net)</span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span></span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a>    <span class="co"># turns list to a dataframe and aggregate repeated rows</span></span>
<span id="cb40-31"><a href="#cb40-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># (source and targets can appear several times)</span></span>
<span id="cb40-32"><a href="#cb40-32" aria-hidden="true" tabindex="-1"></a>    <span class="co"># weight is the number of times that appears</span></span>
<span id="cb40-33"><a href="#cb40-33" aria-hidden="true" tabindex="-1"></a>    network <span class="op">=</span> pd.concat(df_list)</span>
<span id="cb40-34"><a href="#cb40-34" aria-hidden="true" tabindex="-1"></a>    network <span class="op">=</span> network[network[<span class="st">"source"</span>] <span class="op">!=</span> network[<span class="st">"target"</span>]]</span>
<span id="cb40-35"><a href="#cb40-35" aria-hidden="true" tabindex="-1"></a>    df_network <span class="op">=</span> (</span>
<span id="cb40-36"><a href="#cb40-36" aria-hidden="true" tabindex="-1"></a>        network.groupby([<span class="st">"source"</span>, <span class="st">"target"</span>])</span>
<span id="cb40-37"><a href="#cb40-37" aria-hidden="true" tabindex="-1"></a>        .size()</span>
<span id="cb40-38"><a href="#cb40-38" aria-hidden="true" tabindex="-1"></a>        .reset_index(name<span class="op">=</span><span class="st">"weight"</span>)</span>
<span id="cb40-39"><a href="#cb40-39" aria-hidden="true" tabindex="-1"></a>        .sort_values(by<span class="op">=</span><span class="st">"weight"</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb40-40"><a href="#cb40-40" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb40-41"><a href="#cb40-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-42"><a href="#cb40-42" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> df_network</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:14.933976Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:09.819558Z&quot;}" data-execution_count="34">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>df_castaway_network <span class="op">=</span> build_network(df_network, <span class="st">"std_name"</span>, <span class="st">"std_artist"</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co"># most conected pair of people</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>df_castaway_network[:<span class="dv">10</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="34">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">source</th>
<th data-quarto-table-cell-role="th">target</th>
<th data-quarto-table-cell-role="th">weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">209492</td>
<td>denis matthews</td>
<td>itzhak perlman</td>
<td>6</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">36398</td>
<td>andor foldes</td>
<td>hephzibah menuhin</td>
<td>6</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">297911</td>
<td>george cansdale</td>
<td>rowland emett</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">522899</td>
<td>vernon scannell</td>
<td>vladimir ashkenazy</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">209556</td>
<td>denis matthews</td>
<td>jeremy thorpe</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">36724</td>
<td>andor foldes</td>
<td>mitsuko uchida</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">209389</td>
<td>denis matthews</td>
<td>gerald moore</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">36108</td>
<td>andor foldes</td>
<td>catherine gaskin</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">285657</td>
<td>fred hoyle</td>
<td>vladimir ashkenazy</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">209425</td>
<td>denis matthews</td>
<td>hardy amies</td>
<td>5</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>To understand what the table above describes, we can look at the choices of the top two pairs, in which the castaways are connected by some of the usual suspects of classical music. Pianist <a href="https://www.bbc.co.uk/programmes/p009y2gb">Denis Matthews (1967)</a> and violinist <a href="https://www.bbc.co.uk/programmes/p009mysv">Itzhak Perlman (1978)</a> both went with Bach, Beethoven, Brahms, Elgar, Mozart and Schubert. <a href="https://www.bbc.co.uk/programmes/p009y841">Hephzibah Menuhin (1958)</a> and <a href="https://www.bbc.co.uk/programmes/p009y7h7">Andor Foldes (1959)</a> - both pianists - included Bach, Bartók, Beethoven, Brahms, Mozart and Schubert in their lists.</p>
<p>Now we can feed this data to a network library to build our network.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:16.566806Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:14.936196Z&quot;}" data-execution_count="35">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>G <span class="op">=</span> nx.from_pandas_edgelist(df_castaway_network, edge_attr<span class="op">=</span>[<span class="st">"weight"</span>])</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(nx.info(G))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Graph with 2447 nodes and 523560 edges</code></pre>
</div>
</div>
<p>Networks have interesting metrics that can help us understand our dataset better. For example, we have the node degree metric, that tells us the number of edges connected to a given node. In our case, the node degree of a castaway will tell us how popular or rare their taste in music is.</p>
<p>Let’s explore who have the highest and lowest node degrees in our network.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:16.592702Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:16.569973Z&quot;}" data-execution_count="36">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># castaways with more degrees (more artist in common with others)</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>node_degrees <span class="op">=</span> G.degree()</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>degree_sequence <span class="op">=</span> <span class="bu">sorted</span>([d <span class="cf">for</span> n, d <span class="kw">in</span> node_degrees], reverse<span class="op">=</span><span class="va">True</span>)  <span class="co"># degree sequence</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>degreeCount <span class="op">=</span> collections.Counter(degree_sequence)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>deg, cnt <span class="op">=</span> <span class="bu">zip</span>(<span class="op">*</span>degreeCount.items())</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="bu">sorted</span>(node_degrees, key<span class="op">=</span><span class="kw">lambda</span> x: x[<span class="dv">1</span>], reverse<span class="op">=</span><span class="va">True</span>)[:<span class="dv">10</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="36">
<pre><code>[('denis matthews', 1345),
 ('vernon scannell', 1243),
 ('hardy amies', 1220),
 ('itzhak perlman', 1206),
 ('bernard levin', 1205),
 ('claudio abbado', 1205),
 ('jeremy thorpe', 1191),
 ('alan alda', 1184),
 ('john updike', 1170),
 ('c day lewis', 1168)]</code></pre>
</div>
</div>
<p>In the top ten, we’ve got three writers, two musicians, a conductor, an actor, a politician, a designer, and a cartoonist/sculptor. Eight of them appeared on the show before 1990, and chose almost exclusively classical music. The two guests from the 1990s - <a href="https://www.bbc.co.uk/programmes/p0093yqy">Alan Alda</a> and <a href="https://www.bbc.co.uk/programmes/p0093pc1">John Updike</a> – chose music spanning classical, jazz, vintage and rock.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:16.607319Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:16.595791Z&quot;}" data-execution_count="37">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># castaways with less degrees (the ones that chose niche stuff)</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="bu">sorted</span>(node_degrees, key<span class="op">=</span><span class="kw">lambda</span> x: x[<span class="dv">1</span>])[:<span class="dv">10</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="37">
<pre><code>[('joan turner', 1),
 ('jack hylton', 1),
 ('dustin hoffman', 1),
 ('jamie cullum', 2),
 ('fenella fielding', 3),
 ('kimberley motley', 4),
 ('m m kaye', 5),
 ('vittorio radice', 5),
 ('roberto alagna', 5),
 ('courtney pine', 5)]</code></pre>
</div>
</div>
<p>Looking at the three castaways with the lowest node degrees, we’ve got actor <a href="https://www.bbc.co.uk/programmes/b01p314n">Dustin Hoffman (2012)</a>, jazz band leader <a href="https://www.bbc.co.uk/programmes/p009y0n5">Jack Hylton (1942)</a>, and comedian and singer <a href="https://www.bbc.co.uk/programmes/p009mfwq">Joan Turner (1988)</a>. Both Hylton and Turner chose their own songs, which might explain their position. For Hoffman, his ranking appears to be as a result of particularly esoteric tastes, picking lesser known artists from jazz, rockabilly and film soundtracks.</p>
</section>
<section id="artists-network" class="level2">
<h2 class="anchored" data-anchor-id="artists-network">Artists network</h2>
<p>Let’s now explore how a network where the nodes are the artists and edges are weighted by the number of castaways that chose them together.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:23.882157Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:16.612796Z&quot;}" data-execution_count="38">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># artist more likely to be chosen toguether</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>df_artists_network <span class="op">=</span> build_network(df_network, <span class="st">"std_artist"</span>, <span class="st">"std_name"</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>df_artists_network[:<span class="dv">10</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="38">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">source</th>
<th data-quarto-table-cell-role="th">target</th>
<th data-quarto-table-cell-role="th">weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">16590</td>
<td>ludwig van beethoven</td>
<td>wolfgang amadeus mozart</td>
<td>162</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">14441</td>
<td>johann sebastian bach</td>
<td>wolfgang amadeus mozart</td>
<td>161</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14247</td>
<td>johann sebastian bach</td>
<td>ludwig van beethoven</td>
<td>148</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">10607</td>
<td>franz schubert</td>
<td>wolfgang amadeus mozart</td>
<td>84</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10521</td>
<td>franz schubert</td>
<td>ludwig van beethoven</td>
<td>75</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">10491</td>
<td>franz schubert</td>
<td>johann sebastian bach</td>
<td>72</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14568</td>
<td>johannes brahms</td>
<td>ludwig van beethoven</td>
<td>62</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">14651</td>
<td>johannes brahms</td>
<td>wolfgang amadeus mozart</td>
<td>62</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14192</td>
<td>johann sebastian bach</td>
<td>johannes brahms</td>
<td>60</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8276</td>
<td>edward elgar</td>
<td>ludwig van beethoven</td>
<td>51</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This list comes as no surprise, as we’ve got another “who’s who” of classical music. In fact, the first nine are simply the various possible combinations of Bach, Beethoven, Brahms, Mozart and Schubert.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:23.893049Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:23.884390Z&quot;}" data-execution_count="39">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>df_artists_network[<span class="op">-</span><span class="dv">10</span>:<span class="op">-</span><span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="39">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">source</th>
<th data-quarto-table-cell-role="th">target</th>
<th data-quarto-table-cell-role="th">weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">6899</td>
<td>della reese</td>
<td>johannes brahms</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6900</td>
<td>della reese</td>
<td>peggy lee</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6901</td>
<td>della reese</td>
<td>the beatles</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6902</td>
<td>della reese</td>
<td>the modern jazz quartet</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6903</td>
<td>denim</td>
<td>irma thomas</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6904</td>
<td>denim</td>
<td>pixies</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6905</td>
<td>denim</td>
<td>radiohead</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6906</td>
<td>denim</td>
<td>the beatles</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6907</td>
<td>denis king</td>
<td>neil diamond</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This list of the bottom ten is less illuminating. Moving down the long tail of more obscure musical artists, we expect there will be lots of pairings that only happen once. For example, in this list is the lesser known Birmingham indie rock band Denim, which was chosen by <a href="https://www.bbc.co.uk/programmes/b09kx840">Charlie Brooker (2018)</a>, the satirist and creator of Black Mirror. His unique musical tastes were captured in the <a href="https://www.bbc.co.uk/programmes/articles/4gmjmCJvY1dSkLD6rngW06n/11-things-we-learned-from-charlie-brooker-s-desert-island-discs">BBC website summary</a> of the episode:</p>
<blockquote class="blockquote">
<p>And for his final track, he selects The New Potatoes by Denim, a “wilfully ridiculous”, high-pitched electronic song that Charlie’s children find as funny as he does. It’s also the disc he would keep over all the others: “There is something darkly amusing about the thought of being stranded there [on the desert island] and the only form of music that you have is that.”</p>
</blockquote>
<p>Denim appearing on Desert Island Discs this one time was worthy of including on their somewhat slim <a href="https://en.wikipedia.org/wiki/Denim_(band)">Wikipedia entry</a>, so it would be surprising to see them with many more pairings. Also, the reason there are only four pairings for Denin is that the other three picks by Brooker were so random that they weren’t found on Spotify (including a song from the children’s programme the Magic Roundabout and the Gameboy theme for Robocop).</p>
<p>Now we can feed this data to a network library to build our network.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:24.040936Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:23.895257Z&quot;}" data-execution_count="40">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>G_artists <span class="op">=</span> nx.from_pandas_edgelist(df_artists_network, edge_attr<span class="op">=</span>[<span class="st">"weight"</span>])</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(nx.info(G_artists))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Graph with 2088 nodes and 19717 edges</code></pre>
</div>
</div>
<p>Let’s take a look at the the node degree of our metric.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:24.048341Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:24.043037Z&quot;}" data-execution_count="41">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get the artist that get more chosen with others</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>node_degrees <span class="op">=</span> G_artists.degree()</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>degree_sequence <span class="op">=</span> <span class="bu">sorted</span>([d <span class="cf">for</span> n, d <span class="kw">in</span> node_degrees], reverse<span class="op">=</span><span class="va">True</span>)  <span class="co"># degree sequence</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>degreeCount <span class="op">=</span> collections.Counter(degree_sequence)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>deg, cnt <span class="op">=</span> <span class="bu">zip</span>(<span class="op">*</span>degreeCount.items())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:24.057614Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:24.050432Z&quot;}" data-execution_count="42">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> artist_bar_plot(artist_names,artist_centrality,genres_central,genre_order, title,ylabel):</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Function to make a bar plot of artists based on a metric (node degree or centrality) """</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create figure and bar plot</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">24</span>, <span class="dv">6</span>))</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>    ax.set_title(title, fontsize<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>    c <span class="op">=</span> sns.color_palette(<span class="st">"Spectral"</span>, <span class="bu">max</span>(<span class="dv">4</span>, <span class="bu">len</span>(np.unique(genre_order))))</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>    colours <span class="op">=</span> {g: c[i] <span class="cf">for</span> i, g <span class="kw">in</span> <span class="bu">enumerate</span>(genre_order)}</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>    ax.bar([a.split(<span class="st">" "</span>)[<span class="op">-</span><span class="dv">1</span>] <span class="cf">for</span>  a <span class="kw">in</span> artist_names], artist_centrality, <span class="dv">1</span>, color<span class="op">=</span>[colours[x] <span class="cf">for</span> x <span class="kw">in</span> genres_central])</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>    labels <span class="op">=</span> <span class="bu">list</span>(colours.keys())</span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a>    handles <span class="op">=</span> [plt.Rectangle((<span class="dv">0</span>, <span class="dv">0</span>), <span class="dv">1</span>, <span class="dv">1</span>, color<span class="op">=</span>colours[x]) <span class="cf">for</span> x <span class="kw">in</span> genre_order]</span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>    ax.legend(handles, labels, facecolor<span class="op">=</span><span class="st">"white"</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># remove y axis and spines</span></span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(ylabel, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a>    plt.xticks(ha<span class="op">=</span><span class="st">'right'</span>, rotation<span class="op">=</span><span class="dv">55</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a>    ax.margins(y<span class="op">=</span><span class="fl">0.1</span>)</span>
<span id="cb53-24"><a href="#cb53-24" aria-hidden="true" tabindex="-1"></a>    plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:24.475629Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:24.059694Z&quot;}" data-execution_count="43">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get info out of dictionary</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>artist_dictionary <span class="op">=</span> <span class="bu">sorted</span>(node_degrees, key<span class="op">=</span><span class="kw">lambda</span> x: x[<span class="dv">1</span>], reverse<span class="op">=</span><span class="va">True</span>)[:<span class="dv">30</span>]</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>artist_names <span class="op">=</span> [artist_dictionary[i][<span class="dv">0</span>] <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>,<span class="bu">len</span>(artist_dictionary))]</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>artist_degree <span class="op">=</span> [artist_dictionary[i][<span class="dv">1</span>] <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>,<span class="bu">len</span>(artist_dictionary))]</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="co"># get genres for the artists and</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>genres_central <span class="op">=</span> [total_df[total_df[<span class="st">'std_artist'</span>]<span class="op">==</span>artist][<span class="st">'genre'</span>].iloc[<span class="dv">0</span>] <span class="cf">for</span> artist <span class="kw">in</span> artist_names]</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>genre_order <span class="op">=</span> <span class="bu">list</span>(<span class="bu">dict</span>.fromkeys(genres_central))</span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>artist_bar_plot(artist_names,artist_degree,genres_central,genre_order,<span class="st">"Most popular artists"</span>,<span class="st">"Artist degree"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-03-09-Desert-Island-Discs_files/figure-html/cell-44-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Looking at the artists with the highest node degrees: in addition to some familiar classical composers, we’ve got the Beatles (the most popular artists for much of the past two decades) and Frank Sinatra (the king of our vintage category).</p>
<p>Now we can look at the artists with less node degree, or the ones less chosen in our dataset.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:24.483965Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:24.477574Z&quot;}" data-execution_count="44">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="bu">sorted</span>(node_degrees, key<span class="op">=</span><span class="kw">lambda</span> x: x[<span class="dv">1</span>])[:<span class="dv">10</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="44">
<pre><code>[('gerard philipe', 1),
 ('lisa kirk', 1),
 ('josef suk', 1),
 ('teddy wilson', 1),
 ('nellie lutcher', 1),
 ('black dyke band', 1),
 ('arthur askey', 1),
 ('morgana king', 1),
 ('iarla o lionaird', 2),
 ('shankar mahadevan', 2)]</code></pre>
</div>
</div>
<p>With the lowest node degrees, one performer that is worthy of note is Arthur Askey, an actor/comedian who appeared as a castaway on the show four times. On two of those appearances, he picked his own comedy routines from the films The Proposal and Band Waggon. Two other castaways included his musical comedy – actress <a href="https://www.bbc.co.uk/programmes/p009y0n8">Pat Kirkwood</a> picked his playful song Worm in 1942 and actor <a href="https://www.bbc.co.uk/programmes/p00949y8">John Mills</a> picked his WWII parody Adolf in 2000 – but that wasn’t enough to increase his node degrees above 1.</p>
<p>Another interesting network analysis metric is node centrality, which assigns numbers or rankings to nodes within a graph corresponding to their network position. Betweenness centrality quantifies the number of times a node acts as a bridge along the shortest path between two other nodes. We can investigate in our case which artists are the more central of our network.</p>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:51.071672Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:24.486127Z&quot;}" data-execution_count="45">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the more "central artists" (interesting results!)</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>bet_cen <span class="op">=</span> nx.betweenness_centrality(G_artists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:51.080552Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:51.073888Z&quot;}" data-execution_count="46">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_top_keys(dictionary, top): </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>    sorted_list <span class="op">=</span> <span class="bu">sorted</span>(dictionary.items(), key<span class="op">=</span><span class="kw">lambda</span> item: item[<span class="dv">1</span>],reverse<span class="op">=</span><span class="va">True</span>) </span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> sorted_list[:top]</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="co"># top ten more central artists</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>top_bet_cen <span class="op">=</span> get_top_keys(bet_cen, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-executetime="{&quot;end_time&quot;:&quot;2022-03-09T14:05:51.323164Z&quot;,&quot;start_time&quot;:&quot;2022-03-09T14:05:51.082884Z&quot;}" data-execution_count="47">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get info out of dictionary</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>artist_dictionary <span class="op">=</span> top_bet_cen</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>artist_names <span class="op">=</span> [artist_dictionary[i][<span class="dv">0</span>] <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>,<span class="bu">len</span>(artist_dictionary))]</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>artist_centrality <span class="op">=</span> [artist_dictionary[i][<span class="dv">1</span>] <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>,<span class="bu">len</span>(artist_dictionary))]</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="co"># get genres for the artists and</span></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>genres_central <span class="op">=</span> [total_df[total_df[<span class="st">'std_artist'</span>]<span class="op">==</span>artist][<span class="st">'genre'</span>].iloc[<span class="dv">0</span>] <span class="cf">for</span> artist <span class="kw">in</span> artist_names]</span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>artist_bar_plot(artist_names,artist_centrality,genres_central,genre_order,<span class="st">"Most central artists"</span>,<span class="st">"Artist network centrality"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2022-03-09-Desert-Island-Discs_files/figure-html/cell-48-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>In terms of betweenness, Mozart tops the classical composers, the Beatles come second, and Sinatra, Dylan and Bowie make the top ten.</p>
<p>The network analysis we have presented in this story is a very simple and naive one, a lot more could be explored using these kinds of techniques. For example, we could use community detection algorithms to explore the network structure and group artists or castaways together, also we could look at the time evolution of the networks to better understand how the cultural landscape of the UK has changed in the last 80 years. We invite the reader to investigate these ideas further!</p>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>In this data story, we’ve been looking at some of the trends of people and music on Desert Island Discs. As a mainstay of the BBC Radio schedule, it likely will continue for many decades to come, and this analysis could be continued at future milestones.</p>
<p>In this data story, we’ve identified a number of trends: - Male castaways greatly outnumber female castaways, with the shift to a more representative gender balance about 10 years ago. - The age of castaways has increased over time, with a clear trend decade by decade. - The majority of castaways were born in the UK, but guests born in North America were a substantial percentage of early guests. - In the early days of the programme, about half of the castaways were actors; while that percentage has decreased over time, the primary professions continue to be in the creative industries. - The genres of music chosen on the show have evolved substantially over time, with classical music dominant until the mid-1980s, but current choices spread across a much wider range of genres. - When looking at genres chosen by different professions, athletes and bussinesspeople appear to have more popular tastes. - The network analysis reveals interesting connections between castaways and musical artists, with centrality reflecting the most popular, timeless music and artists, across multiple genres.</p>
<p>After discovering the Desert Island Discs dataset, and some exploratory analysis, this project grew into a fairly long data story. To keep things focused, there are elements of this process that we mention but don’t go into much detail about, and more complicated analysis for which we found a workable shortcut. Future data stories could pick up on a few of these threads, for example data scraping from Wikipedia. Spotify also provides a data for each song that we didn’t use, like danceability, and, as noted above, we could also algorithmically create the metagenres from the microgenres.</p>
<p>It’s worth mentioning again that the data we used was incomplete. Wikipedia did not have complete information about all castaways, and we didn’t always find matches for songs on Spotify. As examples, we were missing information about gender for around 1.5% of castaways, and we were missing profession information for around 10%. While this best-effort attempt limits our analysis somewhat, it is unlikely to substantially change our main findings.</p>
<section id="invited-back-to-the-island" class="level2">
<h2 class="anchored" data-anchor-id="invited-back-to-the-island">Invited back to the island</h2>
<p>As a listener, each Friday and Sunday morning we are invited back to the island to hear someone’s life story through music. But there are some very special guests who are invited back more than once. We close this story by looking at environmentalist and broadcaster David Attenborough’s four episodes.</p>
<p>As a fresh 30-year-old TV presenter for his first appearance with Roy Plomley (<a href="https://www.bbc.co.uk/programmes/p009y8xh">06/05/1957</a>), his first disc was Trouble in Mind by Northern Irish blues singer Ottilie Patterson and Chris Barber Jazz Band. When he returned at the age of 52 (<a href="https://www.bbc.co.uk/programmes/p009mxny">10/03/1979</a>), he requested to take the book Shifts and Expedients of Camp Life by William Barry Lord to the island, which he consistently requested for his following two appearances. Sue Lawley welcomed back a 72-year-old Attenborough (<a href="https://www.bbc.co.uk/programmes/p00942qy">25/12/1998</a>) who asked for the luxury of a guitar, having previously taken a piano and binoculars to the island. And finally, for the <a href="https://www.bbc.co.uk/programmes/b01b8yy0">70th Anniversary Episode (29/01/2012)</a>, Kirsty Young invited him back again, now 85, where the track he saved from the waves was the 3rd of Johann Sebastian Bach’s Goldberg Variations.</p>
<p>With any luck, Lauren Laverne will invite Sir David back again soon, at which point he will have the record for the most episodes all to himself. As he reflects once more on his life and favourite songs, perhaps he will talk about his evolution into a trusted voice on climate action. Hopefully, the rising seas of climate change don’t threaten this island haven of music and autobiography.</p>


</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents"><h2 class="anchored quarto-appendix-heading">Reuse</h2><div id="quarto-reuse" class="quarto-appendix-contents"><div><a rel="license" href="https://creativecommons.org/licenses/by/4.0/">https://creativecommons.org/licenses/by/4.0/</a></div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>